# Generated by Django 2.1.1 on 2019-07-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_upder',
            field=models.IntegerField(default=1, verbose_name='下架'),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='type_description',
            field=models.TextField(verbose_name='类型描述'),
        ),
    ]
