# Generated by Django 2.1.1 on 2019-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_date',
            field=models.DateField(blank=True, null=True, verbose_name='出厂日期'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_safeDate',
            field=models.IntegerField(blank=True, null=True, verbose_name='保质期'),
        ),
    ]
