# Generated by Django 2.1.1 on 2019-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20190725_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='goods_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images', verbose_name='图片地址'),
        ),
    ]
